export const LIST_INDEX = 'LIST_INDEX';
export const LIST_THEME = 'LIST_THEME';
export const SIDEBAR_THEMES = 'SIDEBAR_THEMES';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const NEWS_DETAIL = 'NEWS_DETAIL';
export const NEWS_EXTRA = 'NEWS_EXTRA';

export const NEWS_COMMENTS_LONG = 'NEWS_COMMENTS_LONG';
export const NEWS_COMMENTS_SHORT = 'NEWS_COMMENTS_SHORT';